### PR TITLE
V19.3b0

### PR DESCRIPTION
**Pull request by kikocorreoso**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This is my first time trying to work on a conda-forge related issue. Please, just let me know if I'm skipping any step or if there is something wrong.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
thanks @kikocorreoso! Just made a minor planned cleanup of the recipe. Will merge as soon as CI passes.

**Comment by kikocorreoso** [comment]
hi @carlodri 

Thanks for taking care of it.

**Comment by xhochy** [comment]
Thanks @kikocorreoso

**Pull request merged**
