### PR TITLE
Fix outputs' test and entrypoints, set PIP env vars

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Addresses https://github.com/conda-forge/black-feedstock/pull/14#issuecomment-662965245 and https://github.com/conda-forge/black-feedstock/pull/14#issuecomment-662966156.

### CODE REVIEW

**Comment by mbargull** [comment]
@carlodri

**Comment by mbargull** [comment]
Rerendering changes the README to say `black-recipe`/`black-recipe-feedstock` because it takes the toplevel name.
This does not affect the built packages, though. Those should still be only `black`+`blackd`.

**Comment by mbargull** [comment]
Build log shows that we now build without pip downloading things: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=188051&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=c09a5a47-eec3-5700-9284-6f1bd7b23501&l=440

**Comment by carlodri** [comment]
very insightful PR, thank you @mbargull!

**Pull request merged**
