### PR TITLE
improve/fix multiple-output recipe

### LINKED ISSUE #13: noarch/black-19.10b0-py_2.tar.bz2 contains files from other packages
There are many files in [`noarch/black-19.10b0-py_2.tar.bz2`](https://anaconda.org/conda-forge/black/19.10b0/download/noarch/black-19.10b0-py_2.tar.bz2) that perhaps should not be there because they are from different packages:
```
$ tar --list -f black-19.10b0-py_2.tar.bz2 
info/hash_input.json
info/link.json
info/index.json
info/about.json
info/files
info/paths.json
info/git
site-packages/typed_ast-1.4.1.dist-info/INSTALLER
site-packages/typed_ast-1.4.1.dist-info/WHEEL
site-packages/typed_ast-1.4.1.dist-info/METADATA
site-packages/typed_ast-1.4.1.dist-info/RECORD
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
info/test/run_test.bat
site-packages/attr/py.typed
site-packages/attr/_version_info.pyi
site-packages/attr/filters.pyi
site-packages/attr/converters.pyi
site-packages/attr/exceptions.pyi
site-packages/attr/validators.pyi
site-packages/attr/__init__.pyi
info/licenses/LICENSE
site-packages/blib2to3/__init__.py
site-packages/_black_version.py
site-packages/typed_ast/__init__.py
site-packages/regex/__init__.py
site-packages/blib2to3/pgen2/__init__.py
site-packages/pathspec/patterns/__init__.py
site-packages/attr/_config.py
site-packages/pathspec/compat.py
site-packages/attr/filters.py
site-packages/click/_textwrap.py
site-packages/blib2to3/pgen2/token.py
site-packages/attr/__init__.py
site-packages/click/globals.py
site-packages/blib2to3/pgen2/literals.py
site-packages/attr/exceptions.py
site-packages/blib2to3/pygram.py
site-packages/attr/converters.py
site-packages/attr/_version_info.py
site-packages/pathspec/__init__.py
site-packages/click/__init__.py
site-packages/pathspec/tests/test_pathspec.py
site-packages/click/_unicodefun.py
site-packages/pathspec/pattern.py
site-packages/blib2to3/pgen2/grammar.py
site-packages/pathspec/pathspec.py
site-packages/blackd.py
site-packages/attr/_compat.py
site-packages/typed_ast/tests/test_basics.py
site-packages/blib2to3/pgen2/driver.py
site-packages/pathspec/tests/test_util.py
site-packages/blib2to3/pgen2/parse.py
site-packages/click/exceptions.py
site-packages/typed_ast/conversions.py
site-packages/click/formatting.py
site-packages/blib2to3/pgen2/conv.py
site-packages/attr/_funcs.py
site-packages/pathspec/patterns/gitwildmatch.py
site-packages/click/_winconsole.py
site-packages/click/decorators.py
site-packages/attr/validators.py
site-packages/click/_bashcomplete.py
site-packages/typed_ast/ast27.py
site-packages/pathspec/tests/test_gitwildmatch.py
site-packages/click/testing.py
site-packages/typed_ast/ast3.py
site-packages/blib2to3/pgen2/pgen.py
site-packages/click/parser.py
site-packages/click/utils.py
site-packages/pathspec/util.py
site-packages/click/_termui_impl.py
site-packages/blib2to3/pgen2/tokenize.py
site-packages/click/termui.py
site-packages/click/_compat.py
site-packages/appdirs.py
site-packages/click/types.py
site-packages/blib2to3/pytree.py
site-packages/regex/regex.py
site-packages/attr/_make.py
site-packages/click/core.py
site-packages/pathspec/tests/__init__.py
site-packages/regex/_regex_core.py
site-packages/black.py
site-packages/regex/test_regex.py
site-packages/click-7.1.2.dist-info/LICENSE.rst
info/recipe/meta.yaml.template
site-packages/pathspec-0.8.0.dist-info/INSTALLER
site-packages/pathspec-0.8.0.dist-info/WHEEL
site-packages/pathspec-0.8.0.dist-info/RECORD
site-packages/pathspec-0.8.0.dist-info/METADATA
site-packages/pathspec-0.8.0.dist-info/LICENSE
site-packages/appdirs-1.4.4.dist-info/INSTALLER
site-packages/appdirs-1.4.4.dist-info/WHEEL
site-packages/appdirs-1.4.4.dist-info/RECORD
site-packages/appdirs-1.4.4.dist-info/METADATA
site-packages/attrs-19.3.0.dist-info/top_level.txt
site-packages/regex-2020.7.14.dist-info/top_level.txt
site-packages/click-7.1.2.dist-info/top_level.txt
site-packages/appdirs-1.4.4.dist-info/top_level.txt
site-packages/pathspec-0.8.0.dist-info/top_level.txt
site-packages/typed_ast-1.4.1.dist-info/top_level.txt
site-packages/black-19.10b0.dist-info/top_level.txt
site-packages/black-19.10b0.dist-info/entry_points.txt
site-packages/blib2to3/PatternGrammar.txt
site-packages/appdirs-1.4.4.dist-info/LICENSE.txt
site-packages/blib2to3/Grammar.txt
site-packages/black-19.10b0.dist-info/INSTALLER
site-packages/black-19.10b0.dist-info/WHEEL
site-packages/black-19.10b0.dist-info/LICENSE
site-packages/black-19.10b0.dist-info/RECORD
site-packages/black-19.10b0.dist-info/METADATA
site-packages/typed_ast/_ast27.cpython-38-x86_64-linux-gnu.so
site-packages/typed_ast/_ast3.cpython-38-x86_64-linux-gnu.so
site-packages/regex/_regex.cpython-38-x86_64-linux-gnu.so
site-packages/attrs-19.3.0.dist-info/INSTALLER
site-packages/attrs-19.3.0.dist-info/WHEEL
site-packages/attrs-19.3.0.dist-info/LICENSE
site-packages/attrs-19.3.0.dist-info/RECORD
site-packages/attrs-19.3.0.dist-info/METADATA
site-packages/black-19.10b0.dist-info/direct_url.json
site-packages/click-7.1.2.dist-info/INSTALLER
site-packages/click-7.1.2.dist-info/WHEEL
site-packages/click-7.1.2.dist-info/RECORD
site-packages/click-7.1.2.dist-info/METADATA
site-packages/regex-2020.7.14.dist-info/INSTALLER
site-packages/regex-2020.7.14.dist-info/WHEEL
site-packages/regex-2020.7.14.dist-info/RECORD
site-packages/regex-2020.7.14.dist-info/METADATA
info/recipe/build_base.sh
info/test/run_test.sh
```

As a result, conda complains:
```
...
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::black-19.10b0-py_2'.
...
conda.CondaMultiError: Conda was asked to clobber an existing path.
...
Conda no longer clobbers existing paths without the use of the --clobber option
...
```

I can submit more details about my specific environment if this is useful.

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #13

### CODE REVIEW

**Comment by carlodri** [comment]
@xhochy sorry, can you please help me and review this?

what I don't understand is
* why no tests are run for the `black` part of the recipe outputs...
* why the previous build worked fine on my windows machine (both `black` and `blackd` packages)

**Comment by xhochy** [comment]
Does also work locally for me, file output is:

```
./site-packages
./site-packages/black.py
./site-packages/blackd.py
./site-packages/_black_version.py
./site-packages/blib2to3
./site-packages/blib2to3/Grammar.txt
./site-packages/blib2to3/PatternGrammar.txt
./site-packages/blib2to3/__init__.py
./site-packages/blib2to3/pygram.py
./site-packages/blib2to3/pgen2
./site-packages/blib2to3/pgen2/token.py
./site-packages/blib2to3/pgen2/pgen.py
./site-packages/blib2to3/pgen2/__init__.py
./site-packages/blib2to3/pgen2/literals.py
./site-packages/blib2to3/pgen2/grammar.py
./site-packages/blib2to3/pgen2/conv.py
./site-packages/blib2to3/pgen2/parse.py
./site-packages/blib2to3/pgen2/driver.py
./site-packages/blib2to3/pgen2/tokenize.py
./site-packages/blib2to3/pytree.py
./site-packages/black-19.10b0.dist-info
./site-packages/black-19.10b0.dist-info/RECORD
./site-packages/black-19.10b0.dist-info/LICENSE
./site-packages/black-19.10b0.dist-info/direct_url.json
./site-packages/black-19.10b0.dist-info/WHEEL
./site-packages/black-19.10b0.dist-info/entry_points.txt
./site-packages/black-19.10b0.dist-info/top_level.txt
./site-packages/black-19.10b0.dist-info/INSTALLER
./site-packages/black-19.10b0.dist-info/METADATA
./info
./info/licenses
./info/licenses/LICENSE
./info/recipe
./info/recipe/build_base.sh
./info/recipe/conda_build_config.yaml
./info/recipe/meta.yaml
./info/recipe/meta.yaml.template
./info/paths.json
./info/hash_input.json
./info/files
./info/about.json
./info/link.json
./info/index.json
./info/git
```

**Comment by mbargull** [comment]
I was just about to set off all alarm bells because this would've affected a whole lot of other packages, too. We do have a truck load of recipes that do not use `--no-deps` because at some point conda-forge's docs didn't recomment it and `conda-build` is meant to set an environment variable for that.

Thankfully, this seems to affect only `outputs` of recipes. (Which might also be the answer to @carlodri's questions "why the previous build worked fine on my windows machine": If the previous build did not run `pip install` in the `output/script`, then it wasn't affected.)

I'm opening a `conda-build` issues for this.

**Comment by carlodri** [comment]
@mbargull @xhochy I'm still puzzled as to why no tests are run for the `black` part of the recipe outputs...

**Comment by mbargull** [comment]
My best bet is that moving `test` from toplevel to `/outputs[0]/test` could be the reason. `conda-build` does some special handling for outputs whose package name is the same as the toplevel package name.
Meaning, either moving `test` back up or renaming the toplevel to something else like `black-recipe` or something might fix that. For the latter (which I personally prefer) it probably makes sense to also move `/build/{noarch,entry_points}` to `/outputs[0]/build/`. Also, the `blackd` entrypoint should be moved to the `blackd` output in any case.

**Comment by mbargull** [comment]
I took a look at the build log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=187392&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=c09a5a47-eec3-5700-9284-6f1bd7b23501&l=411 and what follows does not look right. This is due to the same `conda-build` issue I opened.
You know what, I'll just open a PR for this feedstock with the changes I think make sense ;).

**Comment by mbargull** [comment]
xref: https://github.com/conda-forge/black-feedstock/pull/15

**Pull request merged**
